---
title: "Binomial Likelihood Benchmarks"
author: "Akarsh Goyal"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Binomial Likelihood Benchmarks}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

This tutorial documents the performance of the solvers for Binomial Likelihood function.

```{r setup}
library(solvers)
library(lattice)
```
# Well Conditioned Problems
## n > p
```{r, fig.width=10, fig.height=10}
set.seed(34)
d <- randomProblem(100, 10, response="binomial", density = 1, rho=0)

# Obtaining fits for each solver and plotting loss vs time graph
f <- getBenchmarks(d$x, d$y, family="binomial", path_length = 10)

# Plot for middle alpha in the path
if (f$path_length > 1) {
    data <- getBenchmarks(d$x, d$y, family="binomial", alpha=f$alpha[(f$path_length %/% 2)+1])
    plt_middle_well <- xyplot(loss ~ time, group = solver, data = data, auto.key = list(corner = c(0.9, 0.9)), type = "l")
    update(plt_middle_well, par.settings = list(fontsize = list(text = 18)))
}


# Plot for 10th alpha in the path
if (f$path_length >= 10) {
    data <- getBenchmarks(d$x, d$y, family="binomial", alpha=f$alpha[10])
    plt_10_well <- xyplot(loss ~ time, group = solver, data = data, auto.key = list(corner = c(0.9, 0.9)), type = "l")
    update(plt_10_well, par.settings = list(fontsize = list(text = 18)))
}

# Plot for last alpha in the path
data <- getBenchmarks(d$x, d$y, family="binomial", alpha=f$alpha[f$path_length])
plt_last_well <- xyplot(loss ~ time, group = solver, data = data, auto.key = list(corner = c(0.9, 0.9)), type = "l")
update(plt_last_well, par.settings = list(fontsize = list(text = 18)))

```


