---
title: "Multinomial Likelihood Benchmarks"
author: "Akarsh Goyal"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Multinomial Likelihood Benchmarks}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

This tutorial documents the performance of the solvers for Multinomial Likelihood function.

```{r setup}
library(solvers)
library(lattice)
```
# Well Conditioned Problems
## n > p
```{r, fig.width=10, fig.height=10}
d <- randomProblem(1000, 50, response="multinomial", density = 1, rho=0)

# Obtaining fits for each solver and plotting loss vs time graph
f <- getBenchmarks(d$x, d$y, family="multinomial")
plt_well1 <- xyplot(loss ~ time, group = solver, data = f, auto.key = list(corner = c(0.9, 0.9)), type = "l")
update(plt_well1, par.settings = list(fontsize = list(text = 18)))
```

## n < p
```{r, fig.width=10, fig.height=10}
d <- randomProblem(50, 200, response="multinomial", density = 1, rho=0)

# Obtaining fits for each solver and plotting loss vs time graph...
f <- getBenchmarks(d$x, d$y, family="multinomial")
plt_well2 <- xyplot(loss ~ time, group = solver, data = f, auto.key = list(corner = c(0.9, 0.9)), type = "l")
update(plt_well2, par.settings = list(fontsize = list(text = 18)))
```

# Badly Conditioned Problems
## n > p
```{r, fig.width=10, fig.height=10}
d <- randomProblem(1000, 50, response="multinomial", density = 1, rho=0.95)

# Obtaining fits for each solver and plotting loss vs time graph
f <- getBenchmarks(d$x, d$y, family="multinomial")
plt_bad1 <- xyplot(loss ~ time, group = solver, data = f, auto.key = list(corner = c(0.9, 0.9)), type = "l")
update(plt_bad1, par.settings = list(fontsize = list(text = 18)))
```

## n < p
```{r, fig.width=10, fig.height=10}
d <- randomProblem(50, 200, response="multinomial", density = 1, rho=0.95)

# Obtaining fits for each solver and plotting loss vs time graph
f <- getBenchmarks(d$x, d$y, family="multinomial")
plt_bad2 <- xyplot(loss ~ time, group = solver, data = f, auto.key = list(corner = c(0.9, 0.9)), type = "l")
update(plt_bad2, par.settings = list(fontsize = list(text = 18)))
```

