---
title: "Poisson: n>p Benchmarks"
author: "Akarsh Goyal"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Poisson: n>p Benchmarks}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(solvers)
```

# Well Conditioned Problems
## n > p
### p = 10
```{r, fig.width=10, fig.height=10}
set.seed(34)
d <- randomProblem(100, 10, response="poisson", density = 1, rho=0)
f <- getBenchmarks(d$x, d$y, family="poisson", path_length = 100)
```

### p = 20
```{r, fig.width=10, fig.height=10}
d <- randomProblem(100, 20, response="poisson", density = 1, rho=0)
f <- getBenchmarks(d$x, d$y, family="poisson", path_length = 100)
```

# Badly Conditioned Problems
## n > p
### p = 10
```{r, fig.width=10, fig.height=10}
d <- randomProblem(100, 10, response="poisson", density = 1, rho=0.95)
f <- getBenchmarks(d$x, d$y, family="poisson", path_length = 100)
```

### p = 20
```{r, fig.width=10, fig.height=10}
d <- randomProblem(100, 20, response="poisson", density = 1, rho=0.95)
f <- getBenchmarks(d$x, d$y, family="poisson", path_length = 100)
```
