# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sparseADMM <- function(x, y, control) {
    .Call(`_solvers_sparseADMM`, x, y, control)
}

denseADMM <- function(x, y, control) {
    .Call(`_solvers_denseADMM`, x, y, control)
}

sparseFISTA <- function(x, y, control) {
    .Call(`_solvers_sparseFISTA`, x, y, control)
}

denseFISTA <- function(x, y, control) {
    .Call(`_solvers_denseFISTA`, x, y, control)
}

sparseSLOPE <- function(x, y, control) {
    .Call(`_solvers_sparseSLOPE`, x, y, control)
}

denseSLOPE <- function(x, y, control) {
    .Call(`_solvers_denseSLOPE`, x, y, control)
}

#' Logistic regression with ADMM
#'
#' @param x predictors
#' @param y response in {-1, 1}
#' @param lambda regularization sequence
#' @param max_passes maximum number of passes
#' @param opt optimal value
#' @param opt_tol relative suboptimality tolerance
#' @export
admm_binom <- function(x, y, lambda, max_passes) {
    .Call(`_solvers_admm_binom`, x, y, lambda, max_passes)
}

sorted_l1_prox <- function(x, lambda) {
    .Call(`_solvers_sorted_l1_prox`, x, lambda)
}

