# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sparseFISTA <- function(x, y, control) {
    .Call(`_solvers_sparseFISTA`, x, y, control)
}

denseFISTA <- function(x, y, control) {
    .Call(`_solvers_denseFISTA`, x, y, control)
}

sparseSLOPE <- function(x, y, control) {
    .Call(`_solvers_sparseSLOPE`, x, y, control)
}

denseSLOPE <- function(x, y, control) {
    .Call(`_solvers_denseSLOPE`, x, y, control)
}

sorted_l1_prox <- function(x, lambda) {
    .Call(`_solvers_sorted_l1_prox`, x, lambda)
}

