# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sparseADMM <- function(x, y, control) {
    .Call(`_solvers_sparseADMM`, x, y, control)
}

denseADMM <- function(x, y, control) {
    .Call(`_solvers_denseADMM`, x, y, control)
}

sparseFISTA <- function(x, y, control) {
    .Call(`_solvers_sparseFISTA`, x, y, control)
}

denseFISTA <- function(x, y, control) {
    .Call(`_solvers_denseFISTA`, x, y, control)
}

